@echo off
title MSB - Turn On Auto
cd /d "%~dp0"
color 0B

echo.
echo   ===========================================================
echo     TURNING ON AUTO - the bot trades its own signals
echo   ===========================================================
echo.

rem --- Node runs the relay: the piece that catches the bot's alerts ---------
where node >nul 2>nul
if errorlevel 1 (
  echo   [X] Node.js is missing. Get it once at nodejs.org, then run this again.
  echo.
  pause
  exit /b 1
)
echo   [1/4] Starting the relay...
start "MSB Alert Relay" /min cmd /k node relay\server.js
timeout /t 3 >nul

rem --- ngrok gives TradingView a way to reach this PC -----------------------
where ngrok >nul 2>nul
if errorlevel 1 (
  echo   [!] ngrok is missing. Everything else still works - only the
  echo       auto-writing needs it. Install ngrok, then run this again.
  set NOTUNNEL=1
) else (
  echo   [2/4] Opening the line to TradingView...
  start "MSB Phone Link" /min cmd /k ngrok http --url=explicit-sprung-produce.ngrok-free.dev 4410
  timeout /t 3 >nul
)

rem --- the secret is generated by the relay on first run --------------------
echo   [3/4] Reading your private webhook address...
set SECRET=
if exist "relay\secret.txt" set /p SECRET=<relay\secret.txt
if "%SECRET%"=="" (
  echo   [X] Could not read relay\secret.txt - let the relay window finish
  echo       starting, then run this again.
  echo.
  pause
  exit /b 1
)
set HOOK=https://explicit-sprung-produce.ngrok-free.dev/hook/%SECRET%

rem --- put it on the clipboard so there is nothing to type ------------------
echo %HOOK%| clip
echo   [4/4] Opening the Bot switch...
start "" http://localhost:4410/bot/%SECRET%

echo.
echo   ===========================================================
echo     DONE. Your webhook address is COPIED - just paste it.
echo   ===========================================================
echo.
echo     %HOOK%
echo.
echo   ONE TIME ONLY, in TradingView:
echo     1. Open your TRADE SIGNAL alert (pencil icon to edit it)
echo     2. Notifications tab
echo     3. Tick "Webhook URL"
echo     4. Click the box and press Ctrl+V
echo     5. Save
echo.
echo   That is it. On the page that opened: TURN AUTOTRADE ON, set your
echo   balance, and the bot places its own trades in NinjaTrader.
echo   Leave the two small windows running while you trade.
echo.
echo   (If TradingView greys out "Webhook URL", that feature needs a
echo    paid plan - everything else still works without it.)
echo.
pause
